#!/bin/bash
#
# Short script to do cross compilation with MXE on Linux
#
# by James Hammons
# (C) 2012 Underground Software
#
echo "Cross compiling for Win32..."
SUFFIX=win32
export PATH=/opt/mxe-32/usr/bin:$PATH
/opt/mxe-32/usr/bin/i686-w64-mingw32.static-qmake-qt5 -o makefile-qt
make CROSS=i686-w64-mingw32.static-

rel=`git log -1 --pretty=format:%ci | cut -d ' ' -f 1 | tr -d -`

